name: CI

on: pull_request

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with: 
                ref: ${{ github.event.pull_request.head.sha }}
            - name: Build
              run: |
                docker build -t mwildehahn/hack-graphql .
            - name: Install
              run: |
                docker run -v `pwd`:/app mwildehahn/hack-graphql composer install
            - name: Test
              run: |
                docker run -v `pwd`:/app mwildehahn/hack-graphql ./vendor/bin/hacktest tests
